### ISSUE TITLE
Missing Atomic library

### ISSUE THREAD

**Issue by br4m1** [oatpp/oatpp#242]
Hello,

I was able to cross-compile a simple API for Clang ARM.
But when I run the executable I get the following error:
`./{executable}: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

The GNU Atomic library is not supported for my target devices (compatibility problems with libraries delivered by chip manfacturer).

I'm not sure but I think Atomic is only used for a spinlock in Oat++, correct me if I'm wrong.
Would there be a sollution where I wouldn't have to use Atomic?

**Comment by lganzzzo** [comment]
Hello @br4m1 ,

Thanks for filing the issue.
Please also share the details of your target device.

> I'm not sure but I think Atomic is only used for a spinlock in Oat++, correct me if I'm wrong.

Atomics aro also used in mem-pools and connection pools, virtual connections, and some more places.

> Would there be a sollution where I wouldn't have to use Atomic?

We'll have to investigate how to implement it in a configurable way with compile options. 

Best Regards,
Leonid

**Comment by br4m1** [comment]
Little update, I won't be using the conflicting libraries, so I can just simply install the shared lib or static link.

On the supported platform page I saw that there was a know Android build, but no docs etc. for compiling with Clang for ARM. I have written a toolchain file for cross-compiling and some documentation. I could contribute this, if u want?

**Comment by lganzzzo** [comment]
Hey @br4m1 , 

That's great that you've managed to find the solution!

> I have written a toolchain file for cross-compiling and some documentation. I could contribute this, if u want?

Sure, that would be awesome!

**Comment by br4m1** [comment]
What would be the best way to contribute it?
Where should I put it etc.?

**Comment by lganzzzo** [comment]
Hey, 
I think just put it in `oatpp/utility/install/android/<script>`
Later we'll move it, once we decide how to organize this better.

**Comment by br4m1** [comment]
Okay.
And the documentation with necessary dependencies etc?

**Comment by lganzzzo** [comment]
Hey,

I think you may put everything in the same folder.
Something like this:

```
- oatpp/utility/install/android/<scripts-as-you-would-want-to-organize-them>
- oatpp/utility/install/android/README.md
```

Also if you have a lot of files there, and you think that you need a separate repo for this, we can create one. Take a look at the https://github.com/oatpp/oatpp-openwrt-feed - maybe you would want to organize it the same way.

The point is, that at the moment we don't have a collection of specialized build scripts (except for OpenWRT) so we don't know a good way to organize it.
And we are open to propositions.

Regards,
Leonid

**Comment by br4m1** [comment]
Okay.

But is "android" the right name? Yes, I'm compiling for ARM, but this device isn't running Android.
Later I will also be cross-compiling for Android. Than I could add that to.
Maybe?:
`oatpp/utility/{architecture}/{os}`

Or as a separate repo:
`oatpp-compile/{architecture}/{os}`
This could give more room for a more organized, deeper look into compiling/cross-compiling Oat++.

**Comment by lganzzzo** [comment]
Hey @br4m1 ,

This sounds good to me.
I've created an empty repo for this purposes - https://github.com/oatpp/oatpp-xcompile

Feel free to send PRs and organize it the way you think is the best.

Regards,
Leonid

**Comment by br4m1** [comment]
I can't fork the repo because its empty. I also can't create a PR.

**Comment by lganzzzo** [comment]
I've just pushed the license file there.
Try to fork it now

**Comment by lganzzzo** [comment]
@br4m1 ,

I've just sent you an invite to that repo. Also I've found that you have already added files on your side, so I cleared my copy that repo.

You should be able to just set new git remote, and push to that repo.

Regards,
Leonid

**Comment by br4m1** [comment]
I will add some files and documentation as soon as possible. I'm still working on some things.

I had a following up question on my issue. It is not ideal for me to install libatomic.so.1 on my target devices, so I tried static linking my application with libatomic.a. That didn't work, still the same error. I think it is because I need to static link libatomic.a with oat++ to.
What do you think is the best place in oat++ to do that and how?

**Comment by lganzzzo** [comment]
Hey @br4m1 ,

I'm not sure what would be the best way of linking libatomic.a statically. 
Actually, I'm thinking of adding an option in oatpp to build it without atomics at all. 

At the moment it seems to be pretty easy to do something like:
```cpp
#ifdef OATPP_BUILD_NO_ATOMICS
  typedef my::mutex::base::atomic::impl atomic;
#else
  typedef std::atomic atomic;
#endif
```
I think it might be a better way, than bothering with libatomic. And more user-friendly.

**Comment by br4m1** [comment]
That sounds pretty good!
When do you think it will be implemented?

**Comment by lganzzzo** [comment]
I want to find time during this week to do it.

**Comment by br4m1** [comment]
Nice!

**Comment by lganzzzo** [comment]
Hey @br4m1 ,

I took a look at adding discussed above functionality and realized that it'll take me a longer time than I expected.

I have to postpone it as I'm currently fully involved in the release preparations and further development.

You can try to hack it on your own or try to link the libatomic as you've previously suggested.

Regards,
Leonid

**Comment by br4m1** [comment]
Hey @lganzzzo ,

I was able to static link libatomic, but that revealed that there were more libs missing.
Some of those libs I won't be able to staticly link, because a shared version needs to be pressent at runtime.
So libatomic isn't a problem anymore, but I will try to fix the other issues.

I hope to commit the files and documentation for cross-compiling this week!

**Comment by lganzzzo** [comment]
Hey @br4m1 ,
That would be great!
I haven't noticed such issues on my own, so it's really nice to have it documented!

**Comment by br4m1** [comment]
Hey @lganzzzo ,

I have a question about some lines in this CMakeList: https://github.com/oatpp/oatpp/blob/master/src/CMakeLists.txt

`if(MSVC OR MINGW)
    target_link_libraries(oatpp PUBLIC ${CMAKE_THREAD_LIBS_INIT} wsock32 ws2_32)
elseif(APPLE)
    target_link_libraries(oatpp PUBLIC ${CMAKE_THREAD_LIBS_INIT})
else(MSVC OR MINGW)
    if(${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
        target_link_libraries(oatpp PUBLIC ${CMAKE_THREAD_LIBS_INIT})
    else(${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
        target_link_libraries(oatpp PUBLIC ${CMAKE_THREAD_LIBS_INIT} atomic)
    endif(${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
endif(MSVC OR MINGW)`

"atomic", in the else statement forces libatomic to link the shared version. If I remove it, I can link the static version to my executable and no shared version is needed.
What is the reason it is there and can I make a PR with this instead (or do you have a beter way of doing it?):
`if(MSVC OR MINGW)
    target_link_libraries(oatpp PUBLIC ${CMAKE_THREAD_LIBS_INIT} wsock32 ws2_32)
elseif(APPLE)
    target_link_libraries(oatpp PUBLIC ${CMAKE_THREAD_LIBS_INIT})
else(MSVC OR MINGW)
    if(${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD" OR ${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
        target_link_libraries(oatpp PUBLIC ${CMAKE_THREAD_LIBS_INIT})
    else(${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD")
        target_link_libraries(oatpp PUBLIC ${CMAKE_THREAD_LIBS_INIT} atomic)
    endif(${CMAKE_SYSTEM_NAME} STREQUAL "FreeBSD" OR ${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
endif(MSVC OR MINGW)`

**Comment by lganzzzo** [comment]
Hey @br4m1 ,

These lines were introduced in https://github.com/oatpp/oatpp/pull/192 ,

> I m not sure if the atomic line is needed for other people who are building for linux.

I'm not sure either. I think we can remove the `atomic` from there. 
@bamkrs 

I think refactoring this block is a good idea.
Please also remove that redundant cmake conditions on `else` and `endif` statements.
It's really hard to read :)

**Comment by br4m1** [comment]
Hello @lganzzzo ,

The atomic line was introduced in the next commit: https://github.com/oatpp/oatpp/commit/63780d65ed882b7d84eae9843fc858495934aab8#diff-95e351a3805a1dafa85bf20b81d086e6 (#113 ) so way before #192 .

In #113 it is stated that in some cases libatomic needs to be specifly linked. I know this is true for C++11 for some environments, so I don't want to break it for some people. But I think this is fine on Linux.

**Comment by lganzzzo** [comment]
Hey @br4m1 ,

Thanks for double-checking!
What if we then just add a cmake-option `OATPP_DO_NOT_LINK_ATOMIC` which is "OFF" by default.

Then we'll have something like this:

```cmake
SET(ADD_LINK_LIBS ${CMAKE_THREAD_LIBS_INIT})

if(MSVC OR MINGW)
    SET(ADD_LINK_LIBS "${ADD_LINK_LIBS} wsock32 ws2_32")
endif()

if(LINUX AND NOT OATPP_DO_NOT_LINK_ATOMIC) 
    SET(ADD_LINK_LIBS "${ADD_LINK_LIBS} atomic")
endif()

target_link_libraries(oatpp PUBLIC ${ADD_LINK_LIBS})
```

**Comment by br4m1** [comment]
I was able to compile on Linux without atomic so maybe just as a default not link atomic for every platform and people can turn it on.

`SET(ADD_LINK_LIBS ${CMAKE_THREAD_LIBS_INIT})

if(MSVC OR MINGW)
    SET(ADD_LINK_LIBS "${ADD_LINK_LIBS} wsock32 ws2_32")
endif()

if(OATPP_DO_LINK_ATOMIC) 
    SET(ADD_LINK_LIBS "${ADD_LINK_LIBS} atomic")
endif()

target_link_libraries(oatpp PUBLIC ${ADD_LINK_LIBS})`

With `OATPP_DO_LINK_ATOMIC` "OFF" as default.

**Comment by br4m1** [comment]
Also what does the following line in https://github.com/oatpp/oatpp/blob/master/CMakeLists.txt , cause I cann't find a place where it is used.

```cmake
option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
```

**Comment by lganzzzo** [comment]
Hey @br4m1 ,

> I was able to compile on Linux without atomic so maybe just as a default not link atomic for every platform and let people turn it on if they somehow need it.

I propose having existing behavior by default. 
And currently, we are linking atomic for Linux by default.

This small change can break existing pipelines, so let's introduce this enhancement gracefully.
And in the future (when we have a better understanding) we can easily change default setting from "OFF" to "ON".

Regards,
Leonid

**Comment by lganzzzo** [comment]
Hey @br4m1 
The `BUILD_SHARED_LIBS` - is cmake flag. See [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html)
If set to "ON" oatpp will be built as a shared lib.

**Comment by br4m1** [comment]
> Hey @br4m1
> The `BUILD_SHARED_LIBS` - is cmake flag. See [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html)
> If set to "ON" oatpp will be built as a shared lib.

Yeah I saw that already. But thanks.

**Comment by lganzzzo** [comment]
Removing comments - as they are irrelevant to the issue ...

**Comment by lganzzzo** [comment]
*discussion irrelevant to issue removed*

**Comment by br4m1** [comment]
Btw, atomic is only `ON` at default if building not for MSVC, MINGW, APPLE or FreeBSD.

**Comment by br4m1** [comment]
I will make a PR.

**Comment by lganzzzo** [comment]
Nice!
